const llantas = [
    {   id: 1,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 2,
        name: "product 2",
        price: "price 2",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 3,
        name: "product 3",
        price: "price 3",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 4,
        name: "product 4",
        price: "price 4",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 5,
        name: "product 5",
        price: "price 5",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 6,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 7,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
  
    
]

const sistemaArrastre = [
    {   id: 1,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 2,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 3,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 4,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 5,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 6,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
    {   id: 7,
        name: "product 1",
        price: "price 1",
        image: "https://m.media-amazon.com/images/I/61qBw-N4g1L._AC_SL1024_.jpg",
    },
  
    
]

export {llantas, sistemaArrastre};